name: harmonoid
description: A beautiful app to play all your music.
publish_to: "none"
version: 0.1.6+5003

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  provider: ^5.0.0
  libwinmedia: ^0.0.4
  flutter_media_metadata:
    git:
      url: https://github.com/alexmercerind/flutter_media_metadata.git
      ref: 7dd8e7e0a6f5934e10cb6261f030ae2170df3fc6
  flutter_acrylic: ^0.0.2
  dart_discord_rpc: ^0.0.2
  fluentui_system_icons: ^1.1.136
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  filepicker_windows: ^2.0.0
  file_selector: ^0.8.2
  file_selector_linux:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_selector/file_selector_linux
  bitsdojo_window: ^0.1.1+1
  flutter_local_notifications: ^5.0.0
  file_picker: ^3.0.0
  permission_handler: ^6.1.1
  share_plus: ^2.1.4
  palette_generator: ^0.3.0
  http: ^0.13.0
  path: ^1.8.0
  url_launcher: ^6.0.3
  google_fonts: ^2.1.0
  implicitly_animated_reorderable_list: ^0.4.0-dev+4

dev_dependencies:
  msix:
    git:
      url: git://github.com/alexmercerind/msix.git
      ref: a2c15a8662dd346b2738ea89538179f532d4f437

flutter:
  uses-material-design: true
  assets:
    - assets/images/about-header.jpg
    - assets/images/collection-album.jpg
    - assets/images/credits-albums.jpg
    - assets/images/credits-tracks.jpg
    - assets/images/credits-artists.jpg
    - assets/images/credits-exception.jpg
    - assets/images/discover-albums.jpg
    - assets/images/discover-tracks.jpg
    - assets/images/discover-artists.jpg
    - assets/images/exception.jpg
    - assets/images/credits-album-art-0.jpg
    - assets/images/credits-album-art-1.jpg
    - assets/images/credits-album-art-2.jpg
    - assets/images/credits-album-art-3.jpg

  fonts:
    - family: "Roboto"
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf

msix_config:
  msix_version: 0.1.6.0
  display_name: Harmonoid
  identity_name: com.alexmercerind.harmonoid
  file_extension: ogg, ogx, aac, m4a, mp3, wma, wav, aiff, flac, opus
  icons_background_color: transparent
  architecture: x64
  capabilities: broadFileSystemAccess, musicLibrary
  vs_generated_images_folder_path: ./windows/msix/assets
  publisher_display_name: Hitesh Kumar Saini
  publisher: E=saini123hitesh@gmail.com, CN=Hitesh Kumar Saini, OU=com.alexmercerind, O=com.alexmercerind, L=Dehradun, S=Uttarakhand, C=IN
  certificate_path: ./windows/msix/certificate.pfx
  store: false
