name: harmonoid
description: Elegant music app to play & manage music library.
publish_to: "none"
version: 0.2.1+5003

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Plugins maintained by github.com/alexmercerind or proprietary to the Harmonoid.

  libmpv:
    path: external/libmpv.dart
  system_media_transport_controls:
    path: external/smtc-win32/bindings/system_media_transport_controls.dart
  mpris_service:
    path: external/mpris_service.dart
  harmonoid_visual_assets:
    path: external/harmonoid_visual_assets
  override_window_destroy:
    path: external/override_window_destroy
  windows_taskbar: ^1.1.0
  dart_discord_rpc: ^0.0.2
  flutter_media_metadata:
    git:
      url: https://github.com/alexmercerind/flutter_media_metadata.git
      ref: harmonoid

  # Third-party plugins.

  share_plus: ^2.1.4
  url_launcher: ^6.0.3
  permission_handler: ^6.1.1
  filepicker_windows: ^2.0.0
  flutter_local_notifications: ^5.0.0
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  file_picker: ^3.0.0
  file_selector: ^0.8.2
  file_selector_linux:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_selector/file_selector_linux

  # Third-party UI widgets or "pure-dart" packages.

  http: ^0.13.0
  path: ^1.8.0
  provider: ^6.0.1
  animations: ^2.0.0
  palette_generator: ^0.3.2
  draggable_scrollbar: ^0.1.0
  fluentui_system_icons: ^1.1.136
  material_floating_search_bar: ^0.3.6
  implicitly_animated_reorderable_list: ^0.4.0-dev+4
  collection: any
  substring_highlight: ^1.0.33

  # Forked plugins & packages to meet requirements.

  desktop:
    git:
      url: https://github.com/alexmercerind/desktop.git
      path: desktop
  bitsdojo_window:
    git:
      url: https://github.com/alexmercerind/bitsdojo_window.git
      path: bitsdojo_window
      ref: 5e6ddd4b58bb357b23541181b4188ce5892ba7a3
  hotkey_manager:
    git:
      url: https://github.com/alexmercerind/hotkey_manager.git
      ref: main
  known_extents_list_view_builder:
    git:
      url: https://github.com/alexmercerind/known_extents_list_view_builder.git

dependency_overrides:
  bitsdojo_window_windows:
    git:
      url: https://github.com/alexmercerind/bitsdojo_window.git
      path: bitsdojo_window_windows
      ref: 5e6ddd4b58bb357b23541181b4188ce5892ba7a3
  bitsdojo_window_linux:
    git:
      url: https://github.com/alexmercerind/bitsdojo_window.git
      path: bitsdojo_window_linux
      ref: 5e6ddd4b58bb357b23541181b4188ce5892ba7a3
  platform: ^3.1.0

dev_dependencies:
  msix:
    git:
      url: git://github.com/alexmercerind/msix.git
      ref: a2c15a8662dd346b2738ea89538179f532d4f437

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/
  fonts:
    - family: "Inter"
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900

msix_config:
  msix_version: 0.2.1.0
  display_name: Harmonoid
  identity_name: com.alexmercerind.harmonoid
  file_extension: ogg, ogx, aac, m4a, mp3, wma, wav, aiff, flac, opus
  icons_background_color: transparent
  architecture: x64
  capabilities: broadFileSystemAccess, musicLibrary
  vs_generated_images_folder_path: ./windows/msix/assets
  publisher_display_name: Hitesh Kumar Saini
  publisher: E=github.com/alexmercerind, CN=Hitesh Kumar Saini, OU=com.alexmercerind, O=com.alexmercerind, L=Dehradun, S=Uttarakhand, C=IN
  certificate_path: ./windows/msix/certificate.pfx
  store: false
