name: harmonoid
description: Plays & manages your music library. Looks beautiful & juicy.
publish_to: "none"
version: 0.3.11+9023

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_layouts:
    path: external/adaptive_layouts
  animations: ^2.0.0
  audio_service: ^0.18.18
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  crypto: ^3.0.3
  drift: ^2.29.0
  dynamic_color: ^1.6.9
  ffi: ^2.1.2
  file_picker: ^10.3.3
  fluentui_system_icons: ^1.1.136
  flutter_discord_rpc: 1.0.0
  flutter_local_notifications: ^19.0.0
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0
  http: ^1.2.1
  identity:
    path: /Users/alexmercerind/identity
  json_annotation: ^4.9.0
  lastfm:
    path: external/lastfm
  lrc: ^1.0.1
  m3_expressive_shapes:
    git:
      url: https://github.com/kekland/m3_expressive_shapes.git
      ref: e023ce817dc087247b59e10660b2eaf3e00ffc38
  measure_size: ^4.0.0
  media_kit: ^1.2.1
  media_kit_libs_android_audio: ^1.3.8
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_macos_audio:
    path: ./libs/macos
  media_kit_libs_windows_audio: ^1.0.9
  media_library:
    path: external/media_library
  mesh_gradient: ^1.3.7
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service.git
      ref: master
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  provider: ^6.0.1
  safe_local_storage: ^2.0.1
  share_plus: ^12.0.1
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.40
  syncfusion_flutter_datagrid: 24.2.7
  syncfusion_flutter_sliders: 24.2.7
  synchronized: ^3.0.0+2
  system_fonts: ^1.0.1
  system_media_transport_controls:
    path: external/smtc-win32/bindings/system_media_transport_controls
  tag_reader:
    path: external/tag_reader
  uri_parser: ^3.0.0
  url_launcher: ^6.1.3
  uuid: ^4.3.3
  win32: ^5.2.0
  windows_taskbar:
    git:
      url: https://github.com/alexmercerind/windows_taskbar.git
      ref: b3273d58aab9d71f61b51a84d5c6fb6cf0821529

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.9.0

dependency_overrides:
  vector_math: 2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/localizations/
    - assets/localizations/localizations/
    - assets/vectors/
    - assets/visuals/
