name: harmonoid
description: Plays & manages your music library. Looks beautiful & juicy.
publish_to: "none"
version: 0.3.8+5017

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_layouts:
    path: external/adaptive_layouts
  animations: ^2.0.0
  audio_service: ^0.18.7
  awesome_notifications: ^0.7.0-beta.5
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2
  drift: ^2.15.0
  dynamic_color: ^1.6.9
  ffi: ^2.1.2
  file_picker: ^6.1.1
  fluentui_system_icons: ^1.1.136
  flutter_lyric:
    git:
      url: https://github.com/alexmercerind/flutter_lyric.git
      ref: master
  flutter_svg: ^1.1.4
  go_router: ^14.2.7
  http: ^1.2.1
  lrc: ^1.0.1
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.4
  media_library:
    path: external/media_library
  mesh_gradient: ^1.3.7
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service.git
      ref: master
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.0.1
  share_plus: ^2.1.4
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
  substring_highlight: ^1.0.33
  syncfusion_flutter_datagrid: 24.2.7
  synchronized: ^3.0.0+2
  system_media_transport_controls:
    path: external/smtc-win32/bindings/system_media_transport_controls.dart
  tag_reader:
    path: external/tag_reader
  uri_parser: ^2.0.2
  url_launcher: ^6.1.3
  uuid: ^4.3.3
  win32: ^5.2.0
  windows_taskbar:
    git:
      url: https://github.com/alexmercerind/windows_taskbar.git
      ref: b3273d58aab9d71f61b51a84d5c6fb6cf0821529

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/localizations/
    - assets/localizations/localizations/
    - assets/vectors/
    - assets/visuals/
